name: Test and formatting of PRs

on:
  pull_request:
    branches: ['dev']
  workflow_dispatch:

jobs:
  code-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run format
      - run: npm run lint
